CREATE DATABASE SENAI_BUGSMUSIC_MANHA

USE SENAI_BUGSMUSIC_MANHA

CREATE TABLE GENEROS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) 
);

CREATE TABLE CANTORES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) 
);

CREATE TABLE BANDAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255)
	,ID_GENERO INT FOREIGN KEY REFERENCES GENEROS(ID) 
);

CREATE TABLE ALBUNS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) SNOT NULL
	,ID_BANDA INT FOREIGN KEY REFERENCES BANDAS(ID)
);

CREATE TABLE MUSICAS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,ID_ALBUM INT FOREIGN KEY REFERENCES ALBUNS(ID)
);

CREATE TABLE BANDAS_CANTORES (
	ID_CANTOR INT FOREIGN KEY REFERENCES CANTORES (ID),
	ID_BANDA INT FOREIGN KEY REFERENCES BANDAS(ID)
);
CREATE TABLE CANTORES_ALBUNS (
	ID_CANTOR INT FOREIGN KEY REFERENCES CANTORES (ID),
	ID_ALBUM INT FOREIGN KEY REFERENCES ALBUNS(ID)
);

DROP TABLE CANTORES_ALBUNS