CREATE DATABASE SENAI_HAROADS_MANHA;

USE SENAI_HAROADS_MANHA;

CREATE TABLE TIPO_HABILIDADES(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE HABILIDADES(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE CLASSES(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE CLASSES_HABILIDADES(
	ID INT IDENTITY PRIMARY KEY,
	ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES (ID),
	ID_HABILIDADE INT FOREIGN KEY REFERENCES HABILIDADES (ID)
);

CREATE TABLE PERSONAGENS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL UNIQUE,
	CAPACIDADE_MAX_VIDA INT,
	CAPACIDADE_MAX_MANA INT,
	DATA_DE_ATUALIZACAO DATETIME,
	DATA_CRIACAO DATETIME,
	ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES
);