UPDATE PERSONAGENS SET NOME = 'Fer7'
WHERE ID = 3

UPDATE CLASSES SET NOME = 'Necromancer'
WHERE ID = 5

SELECT * FROM PERSONAGENS

SELECT * FROM CLASSES

SELECT NOME FROM CLASSES

SELECT * FROM HABILIDADES

SELECT COUNT (*) FROM HABILIDADES

SELECT * FROM CLASSES_HABILIDADES

SELECT ID FROM HABILIDADES ORDER BY ID ASC

SELECT * FROM TIPO_HABILIDADES

SELECT HABILIDADES.NOME, TIPO_HABILIDADES.NOME FROM HABILIDADES INNER JOIN TIPO_HABILIDADES
	ON
HABILIDADES.ID_TIPO_HABILIDADES = TIPO_HABILIDADES.ID

SELECT * FROM PERSONAGENS INNER JOIN CLASSES
ON
PERSONAGENS.ID_CLASSE = CLASSES.ID

SELECT * FROM PERSONAGENS RIGHT JOIN CLASSES ON PERSONAGENS.ID_CLASSE = CLASSES.ID

SELECT * FROM CLASSES_HABILIDADES INNER JOIN HABILIDADES ON CLASSES_HABILIDADES.ID_HABILIDADE = HABILIDADES.ID

SELECT * FROM CLASSES_HABILIDADES INNER JOIN CLASSES ON CLASSES_HABILIDADES.ID_CLASSE = CLASSES.ID

SELECT * FROM CLASSES_HABILIDADES




ALTER TABLE HABILIDADES ADD ID_TIPO_HABILIDADES INT FOREIGN KEY REFERENCES TIPO_HABILIDADES (ID)