--CIRA O DATABASE
CREATE DATABASE HCURSOS_MANHA;

	--USA O DATABASE
	USE HCURSOS_MANHA;

	--CRIA UMA TABELA
	CREATE TABLE CATEGORIAS_CURSOS (
		ID INT IDENTITY PRIMARY KEY
		, NOME VARCHAR(250) NOT NULL UNIQUE
	);

	--CRIA UMA TABELA
	CREATE TABLE ALUNOS (
		ID INT IDENTITY PRIMARY KEY
		,NOME VARCHAR(250) NOT NULL	
	);

	--CRIA UMA TABELA
	CREATE TABLE PROFESSORES (
		ID INT IDENTITY PRIMARY KEY
		,NOME VARCHAR(250) NOT NULL
	);

	/*
		CRIA A TABELA DE CURSOS
		REFERENCIA A CATEGORIA E O PROFESSOR
		PROFESSOR -> CURSOS = 1 PARA MUITOS
		CATEGORIAS -> CURSOS = 1 PARA MUITOS	
	*/
	CREATE TABLE CURSOS(
		ID INT IDENTITY PRIMARY KEY
		,NOME VARCHAR (250) NOT NULL
		,TITULO VARCHAR(250) NOT NULL
		,ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS_CURSOS(ID)
		,ID_PROFESSORES INT FOREIGN KEY REFERENCES PROFESSORES(ID)
	);

	--CRIA UMA TABELA
	CREATE TABLE CURSOS_ALUNOS(
		ID_ALUNOS INT FOREIGN KEY REFERENCES ALUNOS(ID)
		,ID_CURSOS INT FOREIGN KEY REFERENCES CURSOS(ID)
	);