--LISTA OS DADOS DE UMA TABELA, RETORNA TODAS AS COLUNAS
SELECT * FROM CATEGORIAS_CURSOS

--LISTA OS DADOS DE UMA TABELA INFORMANDO QUAIS AS COLUNAS
SELECT NOME, ID FROM CATEGORIAS_CURSOS

--LISTA OS DADOS DE UMA TABELA ONDE O ID SEJA REFERENTE AO ID DADO
SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 1

--LISTA OS DADOS DE UMA TABELA ORDENANDO PELO ID
--ORDENAÇÃO DEFAULT É CRESCENTE SENDO REPRESENTADO POR ASC 
--ORDENAÇÃO SECUNDARIA É DESCENDENTE SENDO REPRESENTADO POR DESC
SELECT * FROM CATEGORIAS_CURSOS ORDER BY ID ASC

-- LISTA TODOS OS DADOS ONDE O ID SEJA 1 OU 3
SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 1 OR ID = 3

-- LISTA TODOS OS DADO QUE POSSUEM ESTRITAMENTE O ID 3 E O NOME DESIGN
SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 3 AND NOME = 'DESIGN'

--LISTA TODOS OS DADOS QUE POSSUEM A LETRA E INDEPENDENTE DA LOCALIZAÇÃO DA LETRA NA PALAVRA
SELECT * FROM CATEGORIAS_CURSOS WHERE NOME LIKE '%E%'

--LISTA TODOS OS DADOS QUE COMEÇAM COM A LETRA "I"
SELECT * FROM CATEGORIAS_CURSOS WHERE NOME LIKE 'I%'

--LISTA TODOS OS DADOS QUE TERMINAM COM A LETRA "A"
SELECT * FROM CATEGORIAS_CURSOS WHERE NOME LIKE '%A'

--LISTA TODOS OS DADOS QUE SEJAM MAIORES DO QUE 1
SELECT * FROM CATEGORIAS_CURSOS WHERE ID > 1

--LISTA TODOS OS DADOS QUE SEJAM MAIORES OU IGUAL QUE 1
SELECT * FROM CATEGORIAS_CURSOS WHERE ID => 1

--LISTA TODOS OS DADOS QUE SEJAM MENORES DO QUE 1
SELECT * FROM CATEGORIAS_CURSOS WHERE ID < 1

--LISTA TODOS OS DADOS QUE SEJAM MENORES OU IGUAIS A 1
SELECT * FROM CATEGORIAS_CURSOS WHERE ID < 1

-- CONTA TODOS OS DADOS DA TABELA
SELECT COUNT (*) FROM CATEGORIAS_CURSOS

--LISTA OS PRIMEIROS 2 DADOS, SENDO DELIMITADO O TAMANHO DA ORDENAÇÃO PELO NÚMERO ÁPÓS A PALAVRA "TOP"
SELECT TOP 2 * FROM CATEGORIAS_CURSOS ORDER BY ID ASC

--EM TERMOS DE APRESENTAÇÃO O NOME É ALTERADO, COMO UMA MASCARA
SELECT ID, NOME AS BATATA FROM CATEGORIAS_CURSOS

--LISTA TODOS OS DADOS ENTRE OS ID´S DADOS
-- O BTWEEN TRABALHA COM >= E <=
SELECT * FROM CATEGORIAS_CURSOS WHERE ID BETWEEN 2 AND 5

--LISTA TODOS OS DADOS QUE NÃO SAO O ID 1
SELECT * FROM CATEGORIAS_CURSOS WHERE NOT ID = 1

--RETORNA TODAS AS CATEGORIAS ONDE O ID SEJA IGUAL A 1, 3 E 4
SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 1 OR ID = 3 OR ID = 4

--RETORNA TODAS AS CATEGORIAS ONDE O ID SEJA IGUAL A 1, 3 E 4
SELECT *FROM CATEGORIAS_CURSOS WHERE ID IN(1,3,4)

--ALTERA OS DADOS DE UMA DETERMINADA COLUNA DA TABELA
UPDATE CATEGORIAS_CURSOS SET NOME = 'Desenvolvimento de Sistemas' 
WHERE ID = 1

--DELETA OS REGISTROS DA TABELA
DELETE FROM CATEGORIAS_CURSOS WHERE ID = 4



SELECT * FROM ALUNOS

--RETORNA EU MESMO
SELECT * FROM ALUNOS WHERE ID = 1
SELECT * FROM ALUNOS WHERE NOME = 'APACHE'

--RETORNA NOMES QUE CONTENHAM A LETRA I
SELECT * FROM ALUNOS WHERE NOME LIKE '%I%'

--RETORNA NOMES QUE COMEÇAM COM A MESMA LETRA DO MEU NOME
SELECT * FROM ALUNOS WHERE NOME LIKE 'A%'

--RETORNA NOMES QUE TERMINEM COM A LETRA O OU A 
SELECT * FROM ALUNOS WHERE NOME LIKE '%O' OR NOME LIKE '%A'

--RETORNA NOMES QUE POSSUEM O ID IGUAL OU ENTRE 3 E 5
SELECT * FROM ALUNOS WHERE ID BETWEEN 3 AND 5

--RETORNA OS NOMES EM ORDEM ALFABETICA
SELECT * FROM ALUNOS  ORDER BY NOME ASC

--DELETA UMA LINHA QUE POSSUI UM ID
DELETE FROM ALUNOS WHERE ID = 6

--REESCREVE O NOME DA LINHA QUE POSSUI O ID 11
UPDATE ALUNOS SET NOME = 'BARBARA MORALES'
WHERE ID = 11

--RETORNA TODOS OS DADOS DA TABELA DE PROFESSORES
SELECT * FROM PROFESSORES

--RETORNA TODOS OS DADOS DA TABELA DE CURSOS
SELECT * FROM CURSOS

UPDATE CATEGORIAS_CURSOS SET NOME = 'Desenvolvimento'
WHERE ID = 1

--RETORNA O NOME E A QUANTIDADE DE CURSOS AGRUPANDO PELO NOME
SELECT NOME, COUNT(NOME) AS QUANTIDADE_CURSOS FROM CURSOS GROUP BY NOME

--RETORNA TODOS OS CURSOS E SEUS RESPECTIVOS PROFESSORES ATRAVES DO RELACIONAMENTO
SELECT * FROM CURSOS, PROFESSORES WHERE CURSOS.ID_PROFESSORES = PROFESSORES.ID

--RETORNA TODOS OS CURSOS E SEUS RESPECTIVOS PROFESSORES ATRAVES DO RELACIONAMENTO
--USANDO JOIN
SELECT CURSOS.TITULO, PROFESSORES.NOME FROM 
CURSOS INNER JOIN PROFESSORES 
ON
 CURSOS.ID_PROFESSORES = PROFESSORES.ID

 --RETORNA TODOS OS CURSOS E SEUS RESPECTIVOS PROFESSORES ATRAVES DO RELACIONAMENTO
--USANDO JOIN E ABREVIAÇÃO
-- C = CURSOS
-- P = PROFESSORES
SELECT 
	C.NOME AS NOME_CURSOS, 
	P.NOME AS NOME_PROFESSORES
	FROM CURSOS C INNER JOIN PROFESSORES P
ON
C.ID_PROFESSORES = P.ID
AND P.NOME LIKE '%O%' --FAZ UM FILTRO NA QUERY PELO NOME

--RETORNA TODOS OS CURSOS E PROFESSORES MESMO O PROFESSOR NÃO TENDO NENHUM CURSO VINCULADO A ELE
SELECT * FROM
	CURSOS RIGHT JOIN PROFESSORES
ON
	CURSOS.ID_PROFESSORES = PROFESSORES.ID

--RETORNA TODOS OS CURSOS E PROFESSORES MESMO O PROFESSOR NÃO TENDO NENHUM CURSO VINCULADO A ELE
SELECT * FROM
	CURSOS LEFT JOIN PROFESSORES
ON
	CURSOS.ID_PROFESSORES = PROFESSORES.ID

-----------------------------------------EXERCÍCIO--------------------------------------------------------
SELECT * FROM
CURSOS INNER JOIN CATEGORIAS_CURSOS 
ON
 CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID

 SELECT * FROM
	CURSOS LEFT JOIN CATEGORIAS_CURSOS
ON
	CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID

SELECT * FROM
	CURSOS RIGHT JOIN CATEGORIAS_CURSOS
ON
	CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID


SELECT * FROM
	CATEGORIAS_CURSOS INNER JOIN CURSOS
ON
	CATEGORIAS_CURSOS.ID = CURSOS.ID_CATEGORIA

SELECT * FROM
	CATEGORIAS_CURSOS LEFT JOIN CURSOS
ON
	CATEGORIAS_CURSOS.ID = CURSOS.ID_CATEGORIA

SELECT * FROM
	CATEGORIAS_CURSOS RIGHT JOIN CURSOS
ON
	CATEGORIAS_CURSOS.ID = CURSOS.ID_CATEGORIA

SELECT * FROM 
	CURSOS 
	INNER JOIN PROFESSORES ON CURSOS.ID_PROFESSORES = PROFESSORES.ID
	INNER JOIN CATEGORIAS_CURSOS ON CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID

SELECT * FROM 
	CURSOS
	RIGHT JOIN PROFESSORES ON CURSOS.ID_PROFESSORES = PROFESSORES.ID
	RIGHT JOIN CATEGORIAS_CURSOS ON CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID

SELECT * FROM
	CURSOS
	LEFT JOIN PROFESSORES ON CURSOS.ID_PROFESSORES = PROFESSORES.ID
	LEFT JOIN CATEGORIAS_CURSOS ON CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID

SELECT CURSOS.TITULO, PROFESSORES.NOME, CATEGORIAS_CURSOS.NOME FROM
	CURSOS
	INNER JOIN PROFESSORES ON CURSOS.ID_PROFESSORES = PROFESSORES.ID
	INNER JOIN CATEGORIAS_CURSOS ON CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID

SELECT CURSOS.TITULO, PROFESSORES.NOME, CATEGORIAS_CURSOS.NOME FROM
	CURSOS
	RIGHT JOIN PROFESSORES ON CURSOS.ID_PROFESSORES = PROFESSORES.ID
	RIGHT JOIN CATEGORIAS_CURSOS ON CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID

SELECT CURSOS.TITULO, PROFESSORES.NOME, CATEGORIAS_CURSOS.ID FROM
	CURSOS
	LEFT JOIN PROFESSORES ON CURSOS.ID_PROFESSORES = PROFESSORES.ID
	LEFT JOIN CATEGORIAS_CURSOS ON CURSOS.ID_CATEGORIA = CATEGORIAS_CURSOS.ID