--CATEGORIAS-ID,NOME
--INSERE UMA CATEGORIA INFORMANDO A COLUNA
INSERT INTO CATEGORIAS_CURSOS(NOME)
VALUES('Desenvolvimento');

--INSERE UMA CATEGORIA PELA ORDEM DAS COLUNAS
INSERT INTO CATEGORIAS_CURSOS
VALUES('Informática');

--INSERE VARIOS VALORES ATRAVÉS DE UM UNICO INSERT
INSERT INTO CATEGORIAS_CURSOS
VALUES('Design'),('Marketing');

INSERT INTO CATEGORIAS_CURSOS
VALUES('Marketing');

INSERT INTO CATEGORIAS_CURSOS
VALUES('Gestão')

INSERT INTO ALUNOS
VALUES ('APACHE'), ('RENATO'), ('SAULO'), ('RICARDO'), ('BARBARA'), ('GUILHERME');

INSERT INTO PROFESSORES
VALUES('Fernando'), ('Helena'), ('Possarle'), ('Raquel');

INSERT INTO CURSOS (NOME, TITULO, ID_CATEGORIA, ID_PROFESSORES)
VALUES('SQL', 'SQL BÁSICO - PARTE 1', 1, 1), ('SQL', 'SQL BÁSICO - PARTE 2', 1, 1), ('JAVA', 'JAVA BÁSICO - PARTE 2', 1, 2),
('REACT', 'REACT NATIVE - PARTE 1', 1, 2), ('GESTÃO', 'GESTÃO DE PESSOAS', 6, 3);